## **Aprendendo a NumPy**

In [19]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
my_list

[1, 2, 3]

## **NumPy array**

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **NumPy arange**

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2) #step = 2, passa de 2 a 2

array([0, 2, 4, 6, 8])

## **NumPy zeros, ones**

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5)) #(linha,coluna) - dimensao

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [96]:
np.ones(10)*-1

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## **NumPy eye**

In [21]:
np.eye(4) #matriz identidade, já e uma matriz quadratica

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## **NumPy linspace**

In [25]:
np.linspace(0,20,3) #inicial, final e qts numeros dentre esse intervalo

array([ 0., 10., 20.])

In [28]:
np.linspace(0,1,20) # 20 numeros entre 0 e 1, com intervalo fechado

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## **NumPy rand & randn & randint**

In [39]:
np.random.rand(5)

array([0.08991689, 0.54069243, 0.36849949, 0.59478759, 0.60668675])

In [41]:
np.random.rand(3,3) #nao precisa passar uma tupla nesse método

array([[0.90035768, 0.8503749 , 0.63806269],
       [0.91418129, 0.19492051, 0.48108548],
       [0.24255883, 0.64875261, 0.83962998]])

In [45]:
np.random.rand(4)*100 #na numpy, qnd eu multiplo um array, ele multiplica os valores internos

array([91.44807617,  0.71415221, 89.39611083, 39.29588192])

In [48]:
np.random.rand(5, 4, 3) # profundidade, altura e comprimento

array([[[0.95772764, 0.46627836, 0.45363421],
        [0.07157357, 0.16723013, 0.55499348],
        [0.3452131 , 0.63598873, 0.58381028],
        [0.10065338, 0.72393567, 0.38549962]],

       [[0.3522548 , 0.70397048, 0.26045832],
        [0.01695009, 0.24608893, 0.38990747],
        [0.47591528, 0.89378729, 0.39853506],
        [0.65176296, 0.42372383, 0.36379416]],

       [[0.7371705 , 0.60434234, 0.38224132],
        [0.69816916, 0.27160669, 0.02009238],
        [0.98576307, 0.01001165, 0.25415589],
        [0.82756563, 0.2413191 , 0.5080726 ]],

       [[0.33728266, 0.42798581, 0.7495936 ],
        [0.64045811, 0.68163167, 0.97219899],
        [0.48926817, 0.94826174, 0.42077807],
        [0.23071653, 0.39878162, 0.37942982]],

       [[0.44023516, 0.62125564, 0.07253541],
        [0.06195794, 0.5326814 , 0.04036499],
        [0.93416832, 0.24273787, 0.81598969],
        [0.37346034, 0.8413075 , 0.82558474]]])

In [56]:
2.5 * np.random.randn(2,4) + 3 #similar ao rand, mas seus valores sao da distribuicao normal, gaussiana

array([[ 1.4452272 ,  2.69768599,  4.66731917,  3.58000224],
       [ 3.86724037, -0.64279262, -1.58970807,  2.28037762]])

In [57]:
2.5 * np.random.randn(2,4) + 3

array([[ 9.62485307,  4.51236547,  3.37406103, -0.55207241],
       [ 3.76749134, -0.38562874,  2.60376403,  3.71788447]])

In [60]:
np.random.randint(0,100,14) #14 numeros inteiros de 0 a 100, intervalo aberto

array([10, 13, 30, 41, 89, 56, 80, 99, 50, 31, 21, 25, 32, 33])

In [67]:
np.random.randint(2, size=10)

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0])

In [79]:
np.linspace(1,50,10) // 1

array([ 1.,  6., 11., 17., 22., 28., 33., 39., 44., 50.])

## **NumPy round**

In [97]:
np.round(np.linspace(1,50,10),2) #numero de casas decimais apos a virgula

array([ 1.  ,  6.44, 11.89, 17.33, 22.78, 28.22, 33.67, 39.11, 44.56,
       50.  ])

In [91]:
np.round(1.6)

2.0

## **NumPy reshape**

In [128]:
arr = np.random.rand(25)

In [129]:
arr.shape

(25,)

In [130]:
arr

array([0.91909608, 0.85327008, 0.47116362, 0.54817648, 0.92360655,
       0.39910689, 0.50499951, 0.26977254, 0.9371659 , 0.5543844 ,
       0.07788385, 0.6649347 , 0.99334446, 0.94874937, 0.83650061,
       0.74652934, 0.8897469 , 0.08703214, 0.13857887, 0.29844537,
       0.71805302, 0.89867873, 0.6638469 , 0.67617727, 0.17995152])

In [131]:
arr = np.reshape(arr,(5,5))

In [132]:
arr.shape

(5, 5)

## **NumPy max, min, index**

In [134]:
arr.max()

0.9933444600725287

In [135]:
arr.min()

0.07788384599617049

In [136]:
arr.argmax()

12

In [138]:
arr.argmin()

10